# -*- coding: utf-8 -*-
"""dramas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuisyQ5t_JnIy4aVVuhPuJ_-msG9jWEo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
Xing=pd.read_excel("/content/kdrama.xlsx")
Xing

print(Xing.duplicated())

Xing.info()

cat_col = [col for col in Xing.columns if Xing[col].dtype == 'object']
print('Categorical columns :',cat_col)


num_col = [col for col in Xing.columns if Xing[col].dtype != 'object']
print('Numerical columns :',num_col)

Xing = Xing.dropna()

print(Xing)

from sklearn.preprocessing import LabelEncoder
LabelEncoder()

Xing["Name"] = LabelEncoder().fit_transform(Xing["Name"])
Xing['Cast'] = LabelEncoder().fit_transform(Xing['Cast'])
Xing['Genre'] = LabelEncoder().fit_transform(Xing['Genre'])
Xing['Director'] = LabelEncoder().fit_transform(Xing['Director'])
Xing['Content Rating'] = LabelEncoder().fit_transform(Xing['Content Rating'])
Xing['Screenwriter'] = LabelEncoder().fit_transform(Xing['Screenwriter'])
Xing['Production companies'] = LabelEncoder().fit_transform(Xing['Production companies'])
Xing['Aired Date'] = LabelEncoder().fit_transform(Xing['Aired Date'])
Xing['Duration'] = LabelEncoder().fit_transform(Xing['Duration'])
Xing['Tags'] = LabelEncoder().fit_transform(Xing['Tags'])
Xing['Synopsis'] = LabelEncoder().fit_transform(Xing['Synopsis'])
Xing['Rank'] = LabelEncoder().fit_transform(Xing['Rank'])
Xing['Original Network'] = LabelEncoder().fit_transform(Xing['Original Network'])
Xing['Aired On'] = LabelEncoder().fit_transform(Xing['Aired On'])

Xing[cat_col] = Xing[cat_col].astype(str)

print(Xing)

print(Xing.info())

print(Xing.isna().sum())

Xing

